version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ⬆️
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: main
    directory: /
    commit-message:
      prefix: ⬆️
    schedule:
      interval: daily